library(data.table)
library(ggplot2)
anscombe_complete <- fread("anscombes-quartet-hier.csv")
set_1 <- subset(anscombe_complete,select = c("V2","V3"))
set_2 <- subset(anscombe_complete,select = c("V4","V5"))
set_3 <- subset(anscombe_complete,select = c("V6","V7"))
set_4 <- subset(anscombe_complete,select = c("V8","V9"))
colnames(set_1) <- c("x","y")
colnames(set_2) <- c("x","y")
colnames(set_3) <- c("x","y")
colnames(set_4) <- c("x","y")

anscombes <- c(set_1,set_2,set_3,set_4)
#ggplot(set_1,aes(x,y))+geom_point()
